version: '3'

volumes:
  postgres_data:
    driver: local
  m2_cache:
    driver: local

services:
  java:
    image: openjdk:17
    environment:
      MAVEN_OPTS: >-
        -XX:MaxRAMPercentage=50
        -XX:+UseParallelGC
        -XX:MinHeapFreeRatio=10
        -XX:MaxHeapFreeRatio=20
        -XX:GCTimeRatio=4
        -XX:AdaptiveSizePolicyWeight=90
        -Dsun.zip.disableMemoryMapping=true
        -Xms20m
        -Djava.security.egd=file:/dev/./urandom
      JAVA_OPTS: >-
        -XX:MaxRAMPercentage=50
        -XX:+UseParallelGC
        -XX:MinHeapFreeRatio=10
        -XX:MaxHeapFreeRatio=20
        -XX:GCTimeRatio=4
        -XX:AdaptiveSizePolicyWeight=90
        -Dsun.zip.disableMemoryMapping=true
        -Xms20m
        -Djava.security.egd=file:/dev/./urandom
      JAVA_TOOL_OPTIONS:
        -XX:MaxRAMPercentage=50
        -XX:+UseParallelGC
        -XX:MinHeapFreeRatio=10
        -XX:MaxHeapFreeRatio=20
        -XX:GCTimeRatio=4
        -XX:AdaptiveSizePolicyWeight=90
        -Dsun.zip.disableMemoryMapping=true
        -Xms20m
        -Djava.security.egd=file:/dev/./urandom
    volumes:
      - m2_cache:/root/.m2
      - ./project:/project
    ports:
      - 0.0.0.0:8081:8081
    working_dir: /project
    entrypoint: ["sleep", "infinity"]
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    # 本番環境で使用する場合には、ビルド済みの keycloak イメージを使うこと
    # あと、 HTTPS 必須なので注意
    # See: [Running Keycloak in a container - Keycloak](https://www.keycloak.org/server/containers)
    image: quay.io/keycloak/keycloak:18.0.2
    environment:
      KC_HEALTH_ENABLED: false
      KC_METRICS_ENABLED: false
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    command: ["start-dev"]
    ports:
      - 0.0.0.0:8080:8080
    depends_on:
      - postgres

