version: '3'

volumes:
  postgres_data:
    driver: local
  m2_cache:
    driver: local

services:
  java:
    image: openjdk:17
    environment:
      MAVEN_OPTS: >-
        -XX:MaxRAMPercentage=50
        -XX:+UseParallelGC
        -XX:MinHeapFreeRatio=10
        -XX:MaxHeapFreeRatio=20
        -XX:GCTimeRatio=4
        -XX:AdaptiveSizePolicyWeight=90
        -Dsun.zip.disableMemoryMapping=true
        -Xms20m
        -Djava.security.egd=file:/dev/./urandom
      JAVA_OPTS: >-
        -XX:MaxRAMPercentage=50
        -XX:+UseParallelGC
        -XX:MinHeapFreeRatio=10
        -XX:MaxHeapFreeRatio=20
        -XX:GCTimeRatio=4
        -XX:AdaptiveSizePolicyWeight=90
        -Dsun.zip.disableMemoryMapping=true
        -Xms20m
        -Djava.security.egd=file:/dev/./urandom
      JAVA_TOOL_OPTIONS:
        -XX:MaxRAMPercentage=50
        -XX:+UseParallelGC
        -XX:MinHeapFreeRatio=10
        -XX:MaxHeapFreeRatio=20
        -XX:GCTimeRatio=4
        -XX:AdaptiveSizePolicyWeight=90
        -Dsun.zip.disableMemoryMapping=true
        -Xms20m
        -Djava.security.egd=file:/dev/./urandom
    volumes:
      - m2_cache:/root/.m2
      - ./project:/project
    ports:
      - 0.0.0.0:8080:8080
    working_dir: /project
    entrypoint: ["sleep", "infinity"]
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 18080:8080
    depends_on:
      - postgres

