server:
  address: 0.0.0.0
  port: 8081

keycloak:
  # Keycloak URL
  auth-server-url: "http://keycloak:8080/auth"

  # レルム名を設定
  realm: "SampleApplication"

  # クライアントIDを設定
  resource: "sample-application"
  public-client: true

  # OpenID ConnectのIDトークン属性を設定。
  principal-attribute: "preferred_username"

  # ディレクトリと、アクセス許可のロールを定義
  security-constraints:
    - authRoles:
        - "authorized"
      securityCollections:
        - patterns:
            - "/"
    - authRoles:
        - "user1"
      securityCollections:
        - patterns:
            - "/users/user1"
    - authRoles:
        - "user2"
      securityCollections:
        - patterns:
            - "/users/user2"

